### PR TITLE
Update downsample.py

### PR DESCRIPTION
**Pull request by resuly**
UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').

### CODE REVIEW

**Comment by zhijian-liu** [comment]
Thanks for the PR! There are four more `//` usages in https://github.com/mit-han-lab/torchsparse/blob/master/torchsparse/nn/modules/conv.py. It would be great if you could also fix them. Besides, please configure `pre-commit` locally by `pre-commit install` to enable the pre-commit hook to reformat the code. Thanks!

**Comment by resuly** [comment]
Thank you. The code has been formatted. I haven't found any similar operation in `torchsparse/nn/modules/conv.py`. Are you referring to the `torchsparse/nn/modules/bev.py`? I have fixed issues in that file as well.

**Comment by zhijian-liu** [comment]
Thanks! I was referring to `bev.py`. Could you please change the `rounding_mode` to `trunc` instead (in order to keep backward compatibility)?

**Review by zhijian-liu — APPROVED** [review]
LGTM!

**Pull request merged**
