### PR TITLE
Update FAQ.md

### PR DESCRIPTION
**Pull request by CCInc**

### CODE REVIEW

**Review by zhijian-liu — APPROVED** [review]
Thanks for the PR! I think it would be better for the users to paste the full error messages into the issues (not sure if it will be too long). This is because Gist can be deleted afterward, which is not ideal for archives.

**Comment by CCInc** [comment]
I agree, maybe we could make an issue template that has a field for the error message hidden in a spoiler? It will hide them at least until you view it.

<details> <summary>Spoiler!</summary> erorr msg </details>

**Comment by zhijian-liu** [comment]
That's a good idea!

**Comment by CCInc** [comment]
[Here's the docs to set up a template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-templates), it looks like you might have to configure it. I'm not sure I have permissions. 

Maybe we could add an "installation error" template? That has a field for gcc version, pytorch version,  `ls /usr/lib | grep cuda`, nvcc version, spoiler field for the error log, etc. And any other templates if you had ideas!

**Comment by zhijian-liu** [comment]
I think you might be able to set up the template by creating `.github/ISSUE_TEMPLATE/bug_report.md`. Let me know if you have any permission issues.

**Comment by CCInc** [comment]
@zhijian-liu Please take a look at https://github.com/CCInc/torchsparse/issues/new/choose and let me know what you think

**Comment by CCInc** [comment]
We can add some other templates in as well?

**Comment by CCInc** [comment]
@zhijian-liu you okay to merge?

**Comment by zhijian-liu** [comment]
Yes, it looks good to me!

**Pull request merged**
